name: 'sintr_demo'
version: 0.0.1
description: sample

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  uuid: '>=0.5.0 <0.6.0'
  appengine: ^0.3.0
  googleapis_auth: '>=0.1.1 <0.3.0'
  gcloud: '>=0.2.0+4 <0.3.0'
  logging: '>=0.11.1 <0.12.0'
  crypto: '>=0.9.0 <0.10.0'
  path: any
  sintr_live_common:
    git: https://github.com/lukechurch/sintr_live_common.git
